name: Build for Mac Silicon

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-mac-m1:

    runs-on: [self-hosted, macOS, m1]
    
    steps:
    - uses: actions/checkout@master
      name: checkout
      
    - run: ./scripts/build_macos_native.sh
      name: build-for-mac

    - uses: actions/upload-artifact@master
      with:
         name: tsMuxer
         path: build/bin/mac.zip
      name: upload-artefact
